name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build_test:
    name: Build and run tests
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        #run: mvn -q package --file pom.xml -Dmaven.test.skip=true
        run: mvn -q clean install -Dmaven.test.skip=true
      - name: Run Tests
        run: mvn test

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository_owner }}/tcsstore-image
          # file: Dockerfile
          # tags: ghcr.io/${{ github.repository_owner }}/tcs-store:2.0
          push: true

      - name: Upload code coverage to CODACY
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/target/site/jacoco-aggregate/jacoco.xml

      # - name: Upload code coverage to CODECOV
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: coverage/target/site/jacoco-aggregate/jacoco.xml
      #     fail_ci_if_error: true
      #     verbose: true